package objects

import (
	bpf "github.com/cilium/cilium/pkg/bpf"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SockRevNat4Key) DeepCopyInto(out *SockRevNat4Key) {
	*out = *in
	in.Address.DeepCopyInto(&out.Address)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SockRevNat4Key.
func (in *SockRevNat4Key) DeepCopy() *SockRevNat4Key {
	if in == nil {
		return nil
	}
	out := new(SockRevNat4Key)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyMapKey is an autogenerated deepcopy function, copying the receiver, creating a new bpf.MapKey.
func (in *SockRevNat4Key) DeepCopyMapKey() bpf.MapKey {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SockRevNat4Value) DeepCopyInto(out *SockRevNat4Value) {
	*out = *in
	in.Address.DeepCopyInto(&out.Address)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SockRevNat4Value.
func (in *SockRevNat4Value) DeepCopy() *SockRevNat4Value {
	if in == nil {
		return nil
	}
	out := new(SockRevNat4Value)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyMapValue is an autogenerated deepcopy function, copying the receiver, creating a new bpf.MapValue.
func (in *SockRevNat4Value) DeepCopyMapValue() bpf.MapValue {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
