apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-request
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-request
  template:
    metadata:
      labels:
        app: echo-request
    spec:
      containers:
        - name: echo-request
          image: registry.lqingcloud.cn/library/echo-request:latest
          imagePullPolicy: Always
          args: ["--tls"]
---
apiVersion: v1
kind: Service
metadata:
  name: echo-request
spec:
  ports:
    - name: tcp-8181
      port: 8181
      protocol: TCP
      targetPort: 8181
  selector:
    app: echo-request
  type: ClusterIP
---
# run gateway-api 1.1.0
apiVersion: gateway.networking.k8s.io/v1alpha3
kind: BackendTLSPolicy
metadata:
  name: echo-request
spec:
  targetRefs:
    - kind: Service
      name: echo-request
      group: ""
  validation:
    caCertificateRefs:
      - kind: ConfigMap
        name: default-gateway-tls
        group: ""
    hostname: echo-request-server
---
apiVersion: v1
kind: Secret
metadata:
  name: default-gateway-tls
type: kubernetes.io/tls
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tDQpNSUlER1RDQ0FnR2dBd0lCQWdJSVd6SlA0WGpXK2VNd0RRWUpLb1pJaHZjTkFRRUxCUUF3RVRFUE1BMEdBMVVFDQpBeE1HY25WcGFtbGxNQ0FYRFRjd01ERXdNVEF3TURBd01Gb1lEekl4TnpBd01UQXhNREF3TURBd1dqQVJNUTh3DQpEUVlEVlFRREV3WnlkV2xxYVdVd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUUNsDQphUnR2Y0tWZnFkN0dBSmpVK1Z1RWlhK2RlT2ZQR1d0VVhNSDJtUUIyd0xZN0R6NUg3TUg4S0NwUGNjdDAwY0ZrDQpiT1p5QnN3dFEzT3VRNjF4M0hPemYxbkllY0RoSXZaQUlEN0krano1N2x4QUllTmRTMk9rUEdLMGljSlkyamlwDQpOY0YzenhwUkJDak9paE1yVjh2ZGxYcXpONitkSVFUV0dWV3RnNEc4cis1ZWNjajJpVWdTbHVxTUhhNDZGbS9ZDQpHNmFEUnZRSVpCczRsYlBwMkpPUll4VGY5T3JrT1ZPUzc5WERxRWFudmJVSVdvNElLOW4wellpRFdyR1pMam92DQphbTRQdTZ1ZjQzRE9mZ2xiRUkyZ0t3QjkwZEwralBsbTdCNVBVWkRmWkUrL3YvZjNoK2g4ZmltNWR6cmlYVGVyDQplSG5leGJlV2hzczAxSThuQUNWOUFnTUJBQUdqY3pCeE1BNEdBMVVkRHdFQi93UUVBd0lGb0RBZEJnTlZIU1VFDQpGakFVQmdnckJnRUZCUWNEQVFZSUt3WUJCUVVIQXdJd0RBWURWUjBUQVFIL0JBSXdBREF5QmdOVkhSRUVLekFwDQpnaE5sWTJodkxYSmxjWFZsYzNRdGMyVnlkbVZ5Z2d4bFkyaHZMWEpsY1hWbGMzU0hCSDhBQUFFd0RRWUpLb1pJDQpodmNOQVFFTEJRQURnZ0VCQUhnSUlMRWpMVjNOV2hkT0NidG5HRSt1VWpZbUJQaWhIM3J1RzRoY3d4TEszV0ZnDQo2RHRZdlV0elFWTTdvdzNWaFpsV3NQaTZST1NobkhkazU4bjlLaWVzYTVNWHFrU1pnQXFmRXp2bFY2UVhGVW9sDQpPSVdETk00cWRJcWdEODdsRGFLZlFIY3IrdTdhckkzQ3FzelpoYUxMNHFYL1hjYXJCWEZQNk9jeTZES055S0Z2DQpaK3R5SUF1VFZ1L3NleHlBTExmR0NVRnJVcE1GTkFCWXljbzU2VDhZU2J2Z0xDem5ieWVTQ29PcFRnTVBXUnQ3DQpaVEc0VkhoVkEwOW44TXNNSU1idTJydHVWNERNWlNka0tWVjI2WVpLby9NbGtLMUVyRHdkd2pVd0FYbXJVYkduDQpVdjNZczgwYzlZeHVkTEk1S05DVWh3M0hzbmJCN0ZxNDdsV0JNSmc9DQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQ0KTUlJRW93SUJBQUtDQVFFQXBXa2JiM0NsWDZuZXhnQ1kxUGxiaEltdm5Yam56eGxyVkZ6Qjlwa0Fkc0MyT3c4Kw0KUit6Qi9DZ3FUM0hMZE5IQlpHem1jZ2JNTFVOenJrT3RjZHh6czM5WnlIbkE0U0wyUUNBK3lQbzgrZTVjUUNIag0KWFV0anBEeGl0SW5DV05vNHFUWEJkODhhVVFRb3pvb1RLMWZMM1pWNnN6ZXZuU0VFMWhsVnJZT0J2Sy91WG5ISQ0KOW9sSUVwYnFqQjJ1T2hadjJCdW1nMGIwQ0dRYk9KV3o2ZGlUa1dNVTMvVHE1RGxUa3UvVnc2aEdwNzIxQ0ZxTw0KQ0N2WjlNMklnMXF4bVM0NkwycHVEN3VybitOd3puNEpXeENOb0NzQWZkSFMvb3o1WnV3ZVQxR1EzMlJQdjcvMw0KOTRmb2ZINHB1WGM2NGwwM3EzaDUzc1czbG9iTE5OU1BKd0FsZlFJREFRQUJBb0lCQUVSOVFON2p4WlhXd0djNw0KMkF4WE00MnRkUW0vQmp5NlNiYWtzYXRwcnNkOUEvZHdXRmx2cnVLNXZzc21VeGdMd2dmVEQ1Z25PR09GaW1DZA0KcFRPQUZHZytVdTZ2ZXkyOVREbEJJTDRXM3lpZGlaVUVjeUF1RnhQcDdQVFVGYVMwdHNGWmdNSWEvc3FNN2xpVw0KMDFrZkFVcSttZythL3h3UWovQVdqV05MRUcwUHdROFZCTE9Jb3NtL2ovcklzM3F5Q2VEQm40TnBJZXVDcnFwKw0KclJsNzJaZW0yT3VlVjVtNXFYVVRBci9TRUpKY0hCMGphVU9EVUJwVk1yOXpYK2hqVGxzQ1VoTE5saUpNY1NxOQ0KNURpMCt0TElKTlh0Q0JHUncvV0p1Vi9uY0FpSVRIdHlJaVNzNWp6S2ZNT0d3eUNSRzBNekF0dW5pOSszellZaQ0KU3NyM1FBRUNnWUVBeE5ZeTZjRDg2Y0lFbmZFZkQ3bWpNcUFzM2FSZTZTV1ZRQzY2SHNRN1RTRVdNSE9VMGs1cw0Kd05EVXp4b0NqVks0cHdxdHpCbVpJbUY3a1JuWVpNOTZyT280aStUWE53cjJKMDdTVXcwUlptZWN2bUxMNHU2bA0KQ0czMjNZZVN1ZnVLQTF4dEdDemZJRUJTVHEvd0hzNzcyc2ROUkhhSDFTRTJoK3VuNHFxS01za0NnWUVBMXlESw0Kd3NCS1dMVVQzaXNRUzhDek1peGFRUGxrRVZVdUFVRDZKd2cvTlZsYVVpTE1KQ0cyTkNEdWJJWFVEMVArbEJlaw0KUG91OHk5TDM0WHRETmkrMWMxTHNvTUsrb3A3ZFo4VkR1TTczYS9wV3lrWlRpcVF3eTNnNXBBS2JFUURuL0tlUQ0KTGhFb3JlRWxSbUJ3R245RDBUcGZyZ1lIeHAyN1RzYnBmc2Ewb3hVQ2dZQS8zd215VkU4OVF4bmdibWVYNExNVw0KTUdlZW5FRzRBZHdHY2FNdmJKbVprNHp4dCsrb3RvNFBtelFTNSt2QUZBR2JJcG4yeXErb09sMndYZVNjQWI5YQ0KOEwzY2x5dEd6eVhFNTR6VUtqOWxMV1h0V1gyemE2RGR0V0VQelhoTkpWUkpkdXBubDlmblRUZm9GS3NrTkNJQg0KZ2Y2T29xKzg5d1FNNHVrZFloMXFFUUtCZ1FDOWpPNDdGUlVzL2pnSVRLZHFKOXQ4dk9tMVVFamtvTW9OWHNSTA0KT2cvL29NQmRtTDJJcEkrWGRPQy9qRmVpUGQ4VmU1TkRiUHFvR1RaQ1hjcUY1eG1aQ0pyb3QwOGptSmo3QXl3OQ0KblZjU3RCeGUxQUp1S1dlNUVEQ3htMzRvU0VVZ01FQnc1cnVTSWN3bkszZjdVT0ZmYkhDN3RDS0wxWlVodjFBag0KWFUveVZRS0JnQ3Z4aHExQ1BicENSZTBaSmd4cUhvbFVhNmxWMnFGSThKMk0yU0JDbUhNL0VTMEpOeXV2d0UzSA0KTGxpT3FjMzdiWTVtR1NlWUhBSE1JS2wzNjk5bXZXSVBRa213MnFrTUJmajVnZlR5b25FUjdHajhJMjFTT2tJUQ0KQjdhajZUYlpSc3liRk9KUVBZeGNrQVRPZ1NSV2crY292OXBjUGpPNVkxRXhFM2s2NDgwSQ0KLS0tLS1FTkQgUlNBIFBSSVZBVEUgS0VZLS0tLS0=
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: default-gateway-tls
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDGDCCAgCgAwIBAgIUAkd5ppD1U/kv6+wmn9yGTLJmk7kwDQYJKoZIhvcNAQEL
    BQAwETEPMA0GA1UEAxMGcnVpamllMCAXDTcwMDEwMTAwMDAwMFoYDzIxNjkxMTEz
    MDAwMDAwWjARMQ8wDQYDVQQDEwZydWlqaWUwggEiMA0GCSqGSIb3DQEBAQUAA4IB
    DwAwggEKAoIBAQDW3JtwBP/yB3CFvNHFQt0JOLYIRdYrlpqmu9nC/fZFexmIoboU
    5pCC1bmqzH6nTM8R1ZanzGdOShC+OxTgJe/Uvvt6M3HmdDBEwa425n7xmtx7KtZb
    fQMQYnvO5fCm9e+0SS6tRTS91wvlJBKeCu6eBPFnc2AHl5Ouw0qbxFwAADynKFkZ
    fXPaT+/UfdqUX5LkrqN4WUtk8NL8DfFIV1ArOl50zGM5NF+HCvyAk5cQDxCrgT+q
    +UjPEDJ7zfSpiJ8ir8rVi9Wo8ZSh85bql854bwa2uyuleWndsMA74WWQJE9wgxwc
    ZTUe24nOE4Xl58tD/pwE6HzVRmhFsiUkm9hRAgMBAAGjZjBkMA4GA1UdDwEB/wQE
    AwIBBjASBgNVHRMBAf8ECDAGAQH/AgECMB0GA1UdDgQWBBRGE9ylGa/u+VW3KtRG
    AttEw7xwNDAfBgNVHSMEGDAWgBRGE9ylGa/u+VW3KtRGAttEw7xwNDANBgkqhkiG
    9w0BAQsFAAOCAQEAXACiA0QTzVprfCWWJ4WyOeXWOUz6ol0xXAyI6VjXpvAzPnr2
    XhIYIRcW2yxB5O7Ehw7Cud2XZHNuEg64YzNPb8RqNOU/kGGoKWYRcMDdLU/AJ0Rc
    N363QNMOTullA3wGRKUgJzZuwj6GKjb0x5tiLB272GTY0IKs6WU+cGU6fXt42i2g
    7rZrQ6Yt5+9MdGRmkcvMoOLytRp8W30yBQ3JicwkE8BuRo97P6sqGt/GbUksspVP
    wLnjmuInCbjytD69HPxZL3mnpceaY+GGAsbTElMz2Cad0WhALxICsXv8ZDSJS8IB
    KeSFQFEoDfvG7jPiX/AeOZiGWWxPyqDSQ6Dovg==
    -----END CERTIFICATE-----