# run with gateway-api 1.0.0
# run with nginx-gateway-fabric 1.2.0
# curl --resolve cafe.example.com:18443:172.31.254.6 https://cafe.example.com:18443/coffee --insecure
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: echo-gateway-nginx
spec:
  gatewayClassName: nginx
  listeners:
    - protocol: HTTPS
      port: 18443
      name: https
      tls:
        certificateRefs:
          - kind: Secret
            group: ""
            name: default-gateway-tls
        mode: Terminate
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: echo-request-nginx
spec:
  parentRefs:
    - name: echo-gateway-nginx
      sectionName: https
  hostnames:
    - "cafe.example.com"
    - "echo-request-server"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: "/rewrite-url"
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /
        - type: RequestHeaderModifier
          requestHeaderModifier:
            add:
              - name: "NEW-HEADER"
                value: "NEW-HEADER-VALUE"
      backendRefs:
        - name: echo-request
          port: 8181
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: echo-request
          port: 8181

