# run with gateway-api 1.0.0
# run with nginx-gateway-fabric 1.2.0
# curl --resolve echo-request:18443:172.28.112.118 https://echo-request:18443/coffee --insecure
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: echo-gateway-nginx
spec:
  gatewayClassName: nginx
  listeners:
    - protocol: HTTP
      port: 18443
      name: http
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: echo-request-nginx
spec:
  parentRefs:
    - name: echo-gateway-nginx
      sectionName: http
# 注意：
# 1. 指定 nginx 指定 server_name，此时 Client 只能通过对应域名访问到指定的 server ，使用 IP 访问将返回 404
# 2. 通过指定不同的 server_name ，可以使不同服务共用一个端口，功能类似 ingress
# 3. 如果不指定 server_name，则可以使用 IP 地址访问。
#  hostnames:
#    - "echo-request"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: "/rewrite-url"
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /
        - type: RequestHeaderModifier
          requestHeaderModifier:
            add:
              - name: "NEW-HEADER"
                value: "NEW-HEADER-VALUE"
      backendRefs:
        - name: echo-request
          port: 8181
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: echo-request
          port: 8181

