---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: echo-gateway
spec:
  gatewayClassName: cilium
  listeners:
    - protocol: TLS
      port: 18443
      name: echo-gateway-tls
      tls:
        mode: Passthrough
