apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: gss
  namespace: sp
spec:
  parentRefs:
    - name: rccp-gateway
      sectionName: default
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: "/rccp/rccp/gss"
        - path:
            type: PathPrefix
            value: "/gss"
        - path:
            type: PathPrefix
            value: "/rcdc/gss"
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /
      backendRefs:
        - name: gss-cluster-ip
          port: 9375



