apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: rccptang
  namespace: sp
spec:
  parentRefs:
    - name: rccp-gateway
      sectionName: default
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: "/rccp"
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /
#        - type: RequestHeaderModifier
#          requestHeaderModifier:
#            add:
#              - name: "Host"
#                value: "$host"
#              - name: "X-real-ip"
#                value: "$remote_addr"
#              - name: "X-Forwarded-For"
#                value: "$proxy_add_x_forwarded_for"
#              - name: "Connection"
#                value: "keep-alive"
#              - name: "iac-token"
#                value: "$http_iac_token"
      backendRefs:
        - name: rccptang-cluster-ip
          port: 9250

